export const GAME_TIPS = [
  "Buy low, flip high — that's the hustle.",
  'Stash your bread in the Piggy Bank before someone takes it.',
  "Wildcards multiply your profits — stack 'em like pancakes.",
  'Every candy has a size and two candy prototypes.',
  'Study at lunch, unlock Wildcards. Knowledge is money, and money is power.',
  'Big candy, big risk, big reward. Go big or go home.',
  'The bully takes half your cash. Stash it or lose it.',
  'Some Wildcards keep the bullies off your back. Stay protected.',
  "Clear that debt by Day 5 or it's game over.",
  'Prices shift every period — read the room.',
  'Allowance hits every morning. Spend it wisely.',
  'After the bell, you can hit the books or hit the deli.',
  'The deli got fair prices — good spot to re-up.',
  "Same-type Wildcards stack multiplicatively. Level 'em up!.",
  'Price spike incoming? Load up before the wave hits.',
  'Small candy, small cost — still flips for profit.',
  'You can move product any period. Check your stash.',
  'Some wildcards level up to 3. Higher level, heavier impact.',
  "Inventory has got a cap — move product, don't sit on it.",
  'Flat bonuses + Multiplier Wildcards hit different.',
  "Price dipped? That's not a loss, that's a sale.",
  "Stashed cash is safe cash, but you can't spend what's locked.",
  'Win the minigame, pick your Wildcard. Skill pays.',
  "Check Price History — trends don't lie.",
  'Medium candy is the sweet spot for mid-game moves.',
  'Prices trash today? End the day early, live to trade tomorrow.',
  'Day 5, last period — sell everything!',
  "Every minigame can drop any wildcard. Try \'em all.",
  "Confiscation wipes your whole inventory. Don't hold, fold.",
  'The amount of money you find is proportionate to your wallet',
  'Buy cheap in bulk, wait for the spike, then eat.',
  'Reroll your Wildcard picks — shuffle your luck for the perfect combo.',
  'Instant wildcards can be used once a day.',
];
