// Centralized Joker ID System
// 73 total jokers

export const JOKER_IDS = {
  DOUBLE_UP: 1,
  FLIP_ARTIST: 2,
  ACE_THE_TEST: 31,
  INDUCTIVE_REASONING: 43,
  VARIETY_PACK: 50,
  TAPPED_IN: 6,
  COMBO_PLATTER: 8,
  DATA_COMPRESSION: 9,
  SIXTH_SENSE: 56,
  VACUUM_SEALER: 12,
  PERFECT_BAKE: 15,
  BAKE_SALE: 16,
  HOME_MADE: 17,
  TRIPLE_THREAT: 18,
  TREASURE_CHEST: 66,
  ODD_TODD: 30,
  COCOA_FUTURES: 23,
  SAFE_HOUSE: 67,
  THE_GOOD_OLD_DAYS: 24,
  BEAR_MARKET: 19,
  MARKET_MANIPULATION: 20,
  DEPOSIT_BONUS: 22,
  ROMAN_COIN: 37,
  BULK_DISCOUNT: 47,
  BROKE_AND_HUNGRY: 52,
  FARMERS_CARRY: 11,
  BET_YOU_IM_FASTER: 25,
  HARD_KNOCKS: 26,
  UNDERDOG: 49,
  EVEN_STEVENS: 29,
  PURSUASION: 48,
  SOUR_LOGIC: 46,
  EXTRA_CREDIT: 55,
  DOUBLE_DUTCH: 32,
  EARLY_BIRD: 45,
  GOLDEN_HOUR: 38,
  TRADE_ROUTES: 39,
  MYSTERIOUS_ARTIFACT: 53,
  TROPICAL_IMPORT: 42,
  SUGAR_RUSH: 57,
  LOAN_SHARK: 58,
  GLASS_CANNON: 59,
  CONTRABAND: 60,
  ALL_IN: 61,
  HOT_POTATO: 62,
  COMPOUND_INTEREST: 63,
  REPUTATION: 64,
  STREET_SMARTS: 65,
  MINT_CONDITION: 70,
  KING_SIZE: 71,
  MEDIUM_RARE: 72,
  CLEARANCE_SALE: 73,
  PIGGY_BANK_PRO: 74,
  MARKET_CRASH: 75,
  INFLATION: 76,
  LUCKY_CHARM: 77,
  BULLY_BAIT: 78,
  TEACHERS_SPY: 79,
  CLASS_CLOWN: 80,
  DETENTION_DODGE: 81,
  COLLECTOR: 82,
  MINIMALIST: 83,
  LUCKY_7: 84,
  NIGHT_OWL: 85,
  PENNY_PINCHER: 86,
  TAX_COLLECTOR: 87,
  LAST_STAND: 88,
  MOMENTUM: 89,
  DIVERSIFIER: 90,
  PEAK_HOURS: 91,
  PATIENCE_PAYS: 92,
  SPARE_CHANGE: 93,
} as const;

// Reverse mapping for getting name from ID
export const JOKER_NAMES: Record<number, string> = {
  [JOKER_IDS.DOUBLE_UP]: 'Double Up',
  [JOKER_IDS.FLIP_ARTIST]: 'Flip Artist',
  [JOKER_IDS.ACE_THE_TEST]: 'Ace the Test',
  [JOKER_IDS.INDUCTIVE_REASONING]: 'Inductive Reasoning',
  [JOKER_IDS.TAPPED_IN]: 'Tapped in',
  [JOKER_IDS.COMBO_PLATTER]: 'Combo Platter',
  [JOKER_IDS.DATA_COMPRESSION]: 'Data Compression',
  [JOKER_IDS.VACUUM_SEALER]: 'Vacuum Sealer',
  [JOKER_IDS.PERFECT_BAKE]: 'Perfect Bake',
  [JOKER_IDS.BAKE_SALE]: 'Bake Sale',
  [JOKER_IDS.HOME_MADE]: 'Home Made',
  [JOKER_IDS.TRIPLE_THREAT]: 'Triple Threat',
  [JOKER_IDS.TREASURE_CHEST]: 'Treasure Chest',
  [JOKER_IDS.ODD_TODD]: 'Odd Todd',
  [JOKER_IDS.COCOA_FUTURES]: 'Cocoa Futures',
  [JOKER_IDS.SAFE_HOUSE]: 'Safe House',
  [JOKER_IDS.THE_GOOD_OLD_DAYS]: 'The Good Old Days',
  [JOKER_IDS.BEAR_MARKET]: 'Bear Market',
  [JOKER_IDS.MARKET_MANIPULATION]: 'Market Manipulation',
  [JOKER_IDS.DEPOSIT_BONUS]: 'Deposit Bonus',
  [JOKER_IDS.ROMAN_COIN]: 'Roman Coin',
  [JOKER_IDS.FARMERS_CARRY]: 'Farmers Carry',
  [JOKER_IDS.BET_YOU_IM_FASTER]: "Bet You I'm Faster",
  [JOKER_IDS.HARD_KNOCKS]: 'Hard Knocks',
  [JOKER_IDS.EVEN_STEVENS]: 'Even Stevens',
  [JOKER_IDS.PURSUASION]: 'Pursuasion',
  [JOKER_IDS.SOUR_LOGIC]: 'Sour Logic',
  [JOKER_IDS.DOUBLE_DUTCH]: 'Double Dutch',
  [JOKER_IDS.GOLDEN_HOUR]: 'Golden Hour',
  [JOKER_IDS.TRADE_ROUTES]: 'Trade Routes',
  [JOKER_IDS.MYSTERIOUS_ARTIFACT]: 'Mysterious Artifact',
  [JOKER_IDS.TROPICAL_IMPORT]: 'Tropical Import',
  [JOKER_IDS.EARLY_BIRD]: 'Early Bird',
  [JOKER_IDS.BULK_DISCOUNT]: 'Bulk Discount',
  [JOKER_IDS.UNDERDOG]: 'Underdog',
  [JOKER_IDS.VARIETY_PACK]: 'Variety Pack',
  [JOKER_IDS.BROKE_AND_HUNGRY]: 'Broke and Hungry',
  [JOKER_IDS.EXTRA_CREDIT]: 'Extra Credit',
  [JOKER_IDS.SIXTH_SENSE]: 'Sixth Sense',
  [JOKER_IDS.SUGAR_RUSH]: 'Sugar Rush',
  [JOKER_IDS.LOAN_SHARK]: 'Loan Shark',
  [JOKER_IDS.GLASS_CANNON]: 'Glass Cannon',
  [JOKER_IDS.CONTRABAND]: 'Contraband',
  [JOKER_IDS.ALL_IN]: 'All In',
  [JOKER_IDS.HOT_POTATO]: 'Hot Potato',
  [JOKER_IDS.COMPOUND_INTEREST]: 'Compound Interest',
  [JOKER_IDS.REPUTATION]: 'Reputation',
  [JOKER_IDS.STREET_SMARTS]: 'Street Smarts',
  [JOKER_IDS.MINT_CONDITION]: 'Mint Condition',
  [JOKER_IDS.KING_SIZE]: 'King Size',
  [JOKER_IDS.MEDIUM_RARE]: 'Medium Rare',
  [JOKER_IDS.CLEARANCE_SALE]: 'Clearance Sale',
  [JOKER_IDS.PIGGY_BANK_PRO]: 'Piggy Bank Pro',
  [JOKER_IDS.MARKET_CRASH]: 'Market Crash',
  [JOKER_IDS.INFLATION]: 'Inflation',
  [JOKER_IDS.LUCKY_CHARM]: 'Lucky Charm',
  [JOKER_IDS.BULLY_BAIT]: 'Bully Bait',
  [JOKER_IDS.TEACHERS_SPY]: "Teacher's Spy",
  [JOKER_IDS.CLASS_CLOWN]: 'Class Clown',
  [JOKER_IDS.DETENTION_DODGE]: 'Detention Dodge',
  [JOKER_IDS.COLLECTOR]: 'Collector',
  [JOKER_IDS.MINIMALIST]: 'Minimalist',
  [JOKER_IDS.LUCKY_7]: 'Lucky 7',
  [JOKER_IDS.NIGHT_OWL]: 'Night Owl',
  [JOKER_IDS.PENNY_PINCHER]: 'Penny Pincher',
  [JOKER_IDS.TAX_COLLECTOR]: 'Tax Collector',
  [JOKER_IDS.LAST_STAND]: 'Last Stand',
  [JOKER_IDS.MOMENTUM]: 'Momentum',
  [JOKER_IDS.DIVERSIFIER]: 'Diversifier',
  [JOKER_IDS.PEAK_HOURS]: 'Peak Hours',
  [JOKER_IDS.PATIENCE_PAYS]: 'Patience Pays',
  [JOKER_IDS.SPARE_CHANGE]: 'Spare Change',
};

// Helper function to check if a joker has a specific ID
export function hasJokerById(
  jokers: { id: string | number }[],
  jokerId: string | number
): boolean {
  return jokers.some(
    (j) => j.id === jokerId.toString() || j.id.toString() === jokerId.toString()
  );
}

// Helper function to find a joker by ID
export function findJokerById(
  jokers: { id: string | number }[],
  jokerId: string | number
) {
  return jokers.find(
    (j) => j.id === jokerId.toString() || j.id.toString() === jokerId.toString()
  );
}

// Type for joker ID values
export type JokerId = (typeof JOKER_IDS)[keyof typeof JOKER_IDS];
