// Shared joker icon map — used by JokerCard, StatusIndicators, TransactionModal
export const JOKER_ICON_MAP: Record<string, any> = {
  'Double Up': require('../assets/images/emojis/dice.png'),
  'Flip Artist': require('../assets/images/emojis/bullseye.png'),
  'Geometric Expansion': require('../assets/images/emojis/backpack.png'),
  'Ace the Test': require('../assets/images/emojis/book.png'),
  'Inductive Reasoning': require('../assets/images/emojis/logic.png'),
  'Tapped in': require('../assets/images/emojis/tappedIn.png'),
  'Combo Platter': require('../assets/images/emojis/cafeteria.png'),
  'Triple Threat': require('../assets/images/emojis/trident.png'),
  'Data Compression': require('../assets/images/emojis/gear.png'),
  'Vacuum Sealer': require('../assets/images/emojis/vacuumsealer.png'),
  'Perfect Bake': require('../assets/images/emojis/statusCupcake.png'),
  'Bake Sale': require('../assets/images/emojis/cupcake.png'),
  'Home Made': require('../assets/images/emojis/homemade.png'),
  'Bulk Empire': require('../assets/images/emojis/slowcooker.png'),
  'Treasure Chest': require('../assets/images/emojis/vault.png'),
  'Odd Todd': require('../assets/images/emojis/theater.png'),
  'Cocoa Futures': require('../assets/images/emojis/chocolate.png'),
  'Safe House': require('../assets/images/emojis/shield.png'),
  'Shrinking Glass': require('../assets/images/emojis/magnifyingGlass.png'),
  'Bear Market': require('../assets/images/emojis/bear.png'),
  'Market Manipulation': require('../assets/images/emojis/priceSpike.png'),
  'Deposit Bonus': require('../assets/images/emojis/piggyBank.png'),
  'Roman Coin': require('../assets/images/emojis/coin.png'),
  'Farmers Carry': require('../assets/images/emojis/farmersCarry.png'),
  "Bet You I'm Faster": require('../assets/images/emojis/recess.png'),
  'Hard Knocks': require('../assets/images/doggs/rock.png'),
  'Even Stevens': require('../assets/images/emojis/scale.png'),
  'Sour Logic': require('../assets/images/emojis/magic.png'),
  'Double Dutch': require('../assets/images/emojis/jumpRope.png'),
  'Golden Hour': require('../assets/images/emojis/sunrise.png'),
  'Trade Routes': require('../assets/images/emojis/treasureMap.png'),
  'Mysterious Artifact': require('../assets/images/emojis/artifact.png'),
  'Tropical Import': require('../assets/images/emojis/backpack.png'),
  'Jump Rope Rhythm': require('../assets/images/emojis/jumpRope.png'),
  Pursuasion: require('../assets/images/emojis/talkingHead.png'),
  'Early Bird': require('../assets/images/emojis/sunrise.png'),
  'Bulk Discount': require('../assets/images/emojis/bulkSale.png'),
  Underdog: require('../assets/images/emojis/gym.png'),
  'Variety Pack': require('../assets/images/emojis/bulkSale.png'),
  'Broke and Hungry': require('../assets/images/emojis/priceCrash.png'),
  'Extra Credit': require('../assets/images/emojis/book.png'),
  'Sixth Sense': require('../assets/images/emojis/crystalBall.png'),
  'Sugar Rush': require('../assets/images/emojis/rushing.png'),
  'Loan Shark': require('../assets/images/emojis/shark.png'),
  'Glass Cannon': require('../assets/images/emojis/glassCannon.png'),
  Contraband: require('../assets/images/emojis/x.png'),
  'All In': require('../assets/images/emojis/pokerChips.png'),
  'Hot Potato': require('../assets/images/emojis/fire.png'),
  'Compound Interest': require('../assets/images/emojis/piggyBank.png'),
  Reputation: require('../assets/images/emojis/talkingHead.png'),
  'Street Smarts': require('../assets/images/emojis/streetSmart.png'),
  'Mint Condition': require('../assets/images/emojis/crystalBall.png'),
  'King Size': require('../assets/images/emojis/crown.png'),
  'Medium Rare': require('../assets/images/emojis/mediumRare.png'),
  'Clearance Sale': require('../assets/images/emojis/clearanceSale.png'),
  'Piggy Bank Pro': require('../assets/images/emojis/piggyBank.png'),
  'Market Crash': require('../assets/images/emojis/priceCrash.png'),
  Inflation: require('../assets/images/emojis/priceSpike.png'),
  'Lucky Charm': require('../assets/images/emojis/artifact.png'),
  'Bully Bait': require('../assets/images/emojis/beast.png'),
  "Teacher's Pet": require('../assets/images/emojis/student.png'),
  'Class Clown': require('../assets/images/emojis/theater.png'),
  'Detention Dodge': require('../assets/images/emojis/rushing.png'),
  Collector: require('../assets/images/emojis/collector.png'),
  Minimalist: require('../assets/images/emojis/minimalist.png'),
  'Lucky 7': require('../assets/images/emojis/seven.png'),
  'Night Owl': require('../assets/images/emojis/nightowl.png'),
  'Penny Pincher': require('../assets/images/emojis/cent.png'),
  'Tax Collector': require('../assets/images/emojis/moneyWithWings.png'),
  'Last Stand': require('../assets/images/emojis/sunrise.png'),
  Momentum: require('../assets/images/emojis/swingset.png'),
  Diversifier: require('../assets/images/emojis/2468.png'),
  'Peak Hours': require('../assets/images/emojis/mountain.png'),
  'Patience Pays': require('../assets/images/emojis/clock.png'),
  'Spare Change': require('../assets/images/emojis/coin.png'),
  'Deep Freeze': require('../assets/images/emojis/ice.png'),
  Hoarder: require('../assets/images/emojis/backpack.png'),
  'Penny Wise': require('../assets/images/emojis/cent.png'),
  Survivor: require('../assets/images/emojis/fire.png'),
  'Influencer Shoutout': require('../assets/images/emojis/talkingHead.png'),
  'Hall Pass': require('../assets/images/emojis/hallpass.png'),
};
