import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import seedrandom from 'seedrandom';
import { generateSeededGameData } from '../../utils/generateSeededGameData';
import { saveSeed, loadSeed } from '../utils/persistence';

type SeedContextType = {
  seed: string;
  rng: seedrandom.PRNG;
  setSeed: (newSeed: string) => void;
  gameData: ReturnType<typeof generateSeededGameData>;
  modifyCandyPrice: (candyName: string, period: number, newPrice: number) => void;
  getOriginalCandyPrice: (candyName: string, period: number) => number;
  restoreCandyPrice: (candyName: string, period: number) => void;
};

const SeedContext = createContext<SeedContextType | undefined>(undefined);

export const SeedProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [seed, setSeed] = useState('default-seed');
  const [isLoaded, setIsLoaded] = useState(false);
  
  const rng = useMemo(() => seedrandom(seed), [seed]);
  const [gameData, setGameData] = useState(() => generateSeededGameData(seed));
  const [originalPrices, setOriginalPrices] = useState(() => {
    const data = generateSeededGameData(seed);
    return JSON.parse(JSON.stringify(data.candyPrices));
  });

  // Load saved seed on mount
  useEffect(() => {
    const loadSeedData = async () => {
      const defaultSeed = 'default-seed';
      const savedSeed = await loadSeed(defaultSeed);
      
      if (savedSeed !== seed) {
        setSeed(savedSeed);
        // gameData will be regenerated by the effect below
      }
      setIsLoaded(true);
      
      console.log('Seed loaded:', savedSeed);
    };

    loadSeedData();
  }, []);

  // Save seed whenever it changes
  useEffect(() => {
    if (!isLoaded) return; // Don't save during initial load
    saveSeed(seed);
  }, [seed, isLoaded]);
  
  // Update gameData when seed changes
  useEffect(() => {
    const newGameData = generateSeededGameData(seed);
    setGameData(newGameData);
    setOriginalPrices(JSON.parse(JSON.stringify(newGameData.candyPrices)));
  }, [seed]);
  
  const modifyCandyPrice = (candyName: string, period: number, newPrice: number) => {
    setGameData(prev => {
      const updated = { ...prev };
      updated.candyPrices = { ...prev.candyPrices };
      updated.candyPrices[candyName] = [...prev.candyPrices[candyName]];
      updated.candyPrices[candyName][period] = newPrice;
      return updated;
    });
  };
  
  const getOriginalCandyPrice = (candyName: string, period: number): number => {
    return originalPrices[candyName]?.[period] || 0;
  };
  
  const restoreCandyPrice = (candyName: string, period: number) => {
    const originalPrice = getOriginalCandyPrice(candyName, period);
    modifyCandyPrice(candyName, period, originalPrice);
  };
  
  return (
    <SeedContext.Provider value={{ 
      seed, 
      rng, 
      setSeed, 
      gameData,
      modifyCandyPrice,
      getOriginalCandyPrice,
      restoreCandyPrice
    }}>
      {children}
    </SeedContext.Provider>
  );
};

export const useSeed = () => {
  const context = useContext(SeedContext);
  if (!context) {
    throw new Error("useSeed must be used within a SeedProvider");
  }
  return context;
};
